# Snapfile — VouDeQue Screenshots

devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro"
])

languages([
  "pt-BR"
])

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
dark_mode(true)
override_status_bar(true)
